#!/bin/bash
set -e

git_count_version() {
    local last_version=$(git tag | tail -n1 | sed 's/v//')
    local commits=$(git rev-list "v$last_version"... --count)
    echo "$last_version.$commits"
    echo "$last_version.$commits" | sed 's/\.//g'
}

VERSION_NAME=$(git_count_version | head -n1)

sed -ie "s/versionName \".*\"/versionName \"$VERSION_NAME\"/g" build.gradle

VERSION_CODE=$(git_count_version | tail -n1)

sed -ie "s/versionCode .*/versionCode $VERSION_CODE/g" build.gradle
